const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const existing = require('./app.test.cjs');
const {issue} = require('../tools/activation-codes.cjs');
const root = path.join(__dirname, '..');
const keys = crypto.generateKeyPairSync('ec', {namedCurve:'prime256v1'});
const publicKey = keys.publicKey.export({format:'jwk'});
const code = issue(keys.privateKey, 'Test customer Ștefan');
const item = i => ({id:'item-'+i,name:'Lamp '+i,room:'Kitchen',price:100,value:125});
const inventory = count => ({version:2,rooms:[],items:Array.from({length:count},(_,i)=>item(i)),claims:[]});
const make = (count=12, options={}) => existing.app(inventory(count), {publicKey,...options});

async function main() {
  await existing;
  const a = make(); await a.run('Activation.ready');
  assert.equal(a.run('canAddItem()'),false);
  a.run('openItem()'); assert.equal(a.get('#activation-dialog').open,true);
  assert.equal(a.get('#modal').open,undefined);
  a.get('#activation-code').value='wrong-code';
  await a.get('#activation-form').onsubmit({preventDefault(){}});
  assert.match(a.get('#activation-error').textContent,/Invalid activation/);
  assert.equal(a.run('Activation.isActive()'),false);
  a.get('#activation-code').value=code;
  await a.get('#activation-form').onsubmit({preventDefault(){}});
  assert.equal(a.run('Activation.isActive()'),true);
  assert.equal(a.get('#activation-dialog').open,false);
  assert.equal(a.get('#modal').open,true); // Resumes the blocked Add item action.
  await existing.submit(a,existing.values('Thirteenth item'));
  assert.equal(a.run('data.items.length'),13);
  assert.match(a.get('#inventory-mode').innerHTML,/Activated/);
  assert.doesNotMatch(a.get('#inventory-mode').innerHTML,/13\/12/);
  a.run("openItem('sample-1')");await existing.submit(a,existing.values('Sample copy after activation'));
  assert.equal(a.run('data.items.length'),14);
  assert.equal(a.run('samples.length'),10);
  const reloaded=make(14,{activation:a.storage.get('trackly-activation-v1')});
  await reloaded.run('Activation.ready');
  assert.equal(reloaded.run('Activation.isActive()'),true);
  assert.equal(reloaded.run('Activation.customer()'),'Test customer Ștefan');
  const invalid=make(12,{activation:'true'});await invalid.run('Activation.ready');
  assert.equal(invalid.run('Activation.isActive()'),false);
  const parts=code.split('.');
  const payload=JSON.parse(Buffer.from(parts[1],'base64url'));
  parts[1]=Buffer.from(JSON.stringify({...payload,customer:'Tampered'})).toString('base64url');
  invalid.context.bad=parts.join('.');
  await assert.rejects(invalid.run('Activation.activate(bad)'),/Invalid activation/);
  const otherKeys=crypto.generateKeyPairSync('ec',{namedCurve:'prime256v1'});
  invalid.context.bad=issue(otherKeys.privateKey,'Wrong issuer');
  await assert.rejects(invalid.run('Activation.activate(bad)'),/Invalid activation/);
  const options={publicKey,failWrites:true};const failed=existing.app(inventory(12),options);
  failed.context.code=code;await assert.rejects(failed.run('Activation.activate(code)'),/could not be saved/);
  assert.equal(failed.run('Activation.isActive()'),false);
  assert.equal(failed.run('data.items.length'),12);
  assert.equal(failed.storage.has('trackly-activation-v1'),false);
  const legacy=make(14);await legacy.run('Activation.ready');
  legacy.run("openItem('item-0')");await existing.submit(legacy,existing.values('Retained edit'));
  assert.equal(legacy.run('data.items.length'),14);
  assert.equal(legacy.run('data.items[0].name'),'Retained edit');
  assert.equal(legacy.run('canAddItem()'),false);
  console.log('PASS activation: 12 free items, modal, invalid/tampered/wrong-issuer codes, 13th item, sample copies, reload, storage failure and existing over-limit data');

  const backup=make(1);await backup.run('Activation.ready');
  backup.run(fs.readFileSync(path.join(root,'backup.js'),'utf8'));
  backup.context.twelve=inventory(12);backup.run('Backups.validate(twelve)');
  backup.get('#import-backup').click();
  backup.get('#backup-file').files=[{size:100,text:async()=>JSON.stringify(inventory(13))}];
  await backup.get('#backup-file').onchange();
  assert.equal(backup.get('#activation-dialog').open,true);
  assert.equal(backup.run('data.items.length'),1);
  assert.equal(backup.get('#restore-backup').disabled,true);
  backup.get('#activation-code').value=code;
  await backup.get('#activation-form').onsubmit({preventDefault(){}});
  assert.match(backup.get('#backup-preview').textContent,/13 personal items/);
  assert.equal(backup.get('#restore-backup').disabled,true); // Still needs explicit replacement consent.
  backup.get('#backup-confirm').checked=true;backup.get('#backup-confirm').onchange();
  backup.get('#restore-backup').click();
  assert.equal(backup.run('data.items.length'),13);
  assert.ok(!backup.storage.get('trackly-home-v1').includes('TRACKLY1'));
  const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
  assert.ok(html.indexOf('src="activation.js"')<html.indexOf('src="app.js"'));
  const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');
  assert.ok(sw.includes('./activation.js')&&sw.includes('./activation-key.js'));
  assert.ok(!sw.includes('.local-license')&&!sw.includes('private-key'));
  console.log('PASS activation backup: 12-item import, gated 13-item import, consent after unlock, separate license storage and offline assets');
}
main().catch(error=>{console.error(error);process.exitCode=1});
